kind: pipeline
type: docker
name: default

steps:
  - name: fetch-fds-submodule
    image: alpine/git
    commands:
      # Drone cannot auth to a ssh based repo, so override to https to make use of .netrc
      - git config submodule.fivium-design-system-core.url https://bitbucket.org/fiviumuk/fivium-design-system-core.git
      - git submodule update --init --recursive --remote

  - name: build-frontend
    image: node:10
    commands:
      - cd fivium-design-system-core && npm install && cd ..
      - npm install
      - npx gulp buildAll

  - name: build-java
    image: openjdk:11-jdk-slim
    commands:
      - chmod +x gradlew
      - ./gradlew test checkstyleMain bootWar

  - name: sync-reports
    image: alpine
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/pipelines