kind: pipeline
type: docker
name: default
steps:
  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      # Drone cannot auth to a ssh based repo, so override to https to make use of .netrc
      - git config submodule.fivium-design-system-core.url https://bitbucket.org/fiviumuk/fivium-design-system-core.git
      - git submodule update --init --recursive

  - name: build-fds
    image: node:10
    commands:
      - cd fivium-design-system-core
      - npm install
      - npx gulp build
      - cd ..

  - name: build-frontend
    image: node:10
    commands:
      - npm install
      - npx gulp buildAll

  - name: build-backend
    image: openjdk:11-jdk-slim
    environment:
      SONARCLOUD_TOKEN:
        from_secret: SONARCLOUD_TOKEN
    commands:
      - chmod +x gradlew
      - ./gradlew test jacocoTestReport checkstyleMain bootWar bootJar sonarqube

  - name: publish-docker-develop
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/pipeline-works-authorisations
      tags:
        - develop
      config:
        from_secret: docker_config
    when:
      branch:
        - develop
      status:
        - success

  - name: publish-docker
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/pipeline-works-authorisations
      tags:
        - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config
    when:
      branch:
        - master
        - release/**
        - hotfix/**
        - publish-to-docker
        - rebrand-to-nsta
      status:
        - success

  - name: trivy-build-image
    image: docker:19.03.8
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build -t quay.io/fivium/pipeline-works-authorisations:trivy-scan-target .

  - name: trivy-scan
    image: aquasec/trivy:0.20.0
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: drone-trivy-cache
        path: /root/trivy-cache
      - name: webfiles
        path: /var/webfiles
    commands:
      # timeout set as initial cache population can seemingly take a while sometimes
      - trivy image -f template -t "@contrib/html.tpl" -o build/reports/trivy/trivy-scan.html --timeout 30m --exit-code 1 quay.io/fivium/pipeline-works-authorisations:trivy-scan-target
    when:
      status:
        - success

#  - name: vulnerability-scan-java
#    image: openjdk:11-jdk-slim
#    commands:
#      - chmod +x gradlew
#      - ./gradlew dependencyCheckAnalyze
#    volumes:
#      - name: nvd-db
#        path: /var/nvd-db
#    when:
#      branch: develop

  - name: vulnerability-scan-npm
    image: node:10.12.0
    commands:
      - npm audit > build/reports/npm-audit-report.txt || true # dont fail build if non 0 exit code
    when:
      branch: develop

  - name: sync-reports
    image: alpine:3.12.1
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: deploy-dev-st
    image: plugins/downstream:linux-amd64
    settings:
      server: https://drone.fivium.co.uk
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - fiviumuk/oga-dev-app@master
    when:
      branch:
        - develop
      status:
        - success

  - name: slack-all
    image: plugins/slack:linux-amd64
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: oga-pipelines-builds
      template: |
        *{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>
        Reports published to: http://drone-assets.fivium.local:9090/pwa/{{build.number}}/
    when:
      status: [ success, failure ]

  - name: slack-failure
    image: plugins/slack:linux-amd64
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: oga-pipelines
      template: |
        *{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>
        Reports published to: http://drone-assets.fivium.local:9090/pwa/{{build.number}}/
    when:
      status: failure

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/pwa

  - name: nvd-db
    host:
      path: /home/fivium/nvd-db

  - name: docker-sock
    host:
      path: /var/run/docker.sock

  - name: drone-trivy-cache
    host:
      path: /root/.cache/