package uk.co.ogauthority.pwa.model.entity.enums;


public enum ProjectInformationQuestion {

  PROJECT_NAME,
  PROJECT_OVERVIEW,
  METHOD_OF_PIPELINE_DEPLOYMENT,
  PROPOSED_START_DATE,
  MOBILISATION_DATE,
  EARLIEST_COMPLETION_DATE,
  LATEST_COMPLETION_DATE,
  LICENCE_TRANSFER_PLANNED,
  LICENCE_TRANSFER_DATE,
  COMMERCIAL_AGREEMENT_DATE,
  USING_CAMPAIGN_APPROACH,
  PERMANENT_DEPOSITS_BEING_MADE,
  TEMPORARY_DEPOSITS_BEING_MADE,
  FIELD_DEVELOPMENT_PLAN,
  PROJECT_LAYOUT_DIAGRAM;

}