package uk.co.ogauthority.pwa.model.enums.notify;

/**
 * Enumeration of templates stored in GOV.UK Notify.
 */
public enum NotifyTemplate {

  // Application workflow changes
  REVIEW_AND_SUBMIT_APPLICATION("REVIEW_AND_SUBMIT_APPLICATION_V1"),
  APPLICATION_SUBMITTED("APPLICATION_SUBMITTED_V1"),
  APPLICATION_WITHDRAWN("APPLICATION_WITHDRAWN_V1"),

  CONSENT_REVIEW("CONSENT_REVIEW_V1"),
  CONSENT_REVIEW_RETURNED("CONSENT_REVIEW_RETURNED_V1"),

  // Update requests
  APPLICATION_UPDATE_REQUESTED("APPLICATION_UPDATE_REQUEST_V1"),
  APPLICATION_UPDATE_RESPONDED("APPLICATION_UPDATE_RESPONSE_V1"),
  APPLICATION_UPDATE_ACCEPTED("APPLICATION_UPDATE_ACCEPTED_V1"),

  // Assignment
  CASE_OFFICER_ASSIGNED("CASE_OFFICER_ASSIGNED_V1"),
  CONSULTATION_ASSIGNED_TO_YOU("CONSULTATION_ASSIGNED_TO_YOU_V1"),
  CASE_OFFICER_ASSIGNMENT_FAIL("CASE_OFFICER_ASSIGNMENT_FAIL_V1"),

  // Consultations
  CONSULTATION_RESPONSE_RECEIVED("CONSULTATION_RESPONSE_RECEIVED_V1"),
  CONSULTATION_REQUEST_RECEIVED("CONSULTATION_REQUEST_RECEIVED_V1"),
  CONSULTATION_WITHDRAWN("CONSULTATION_WITHDRAWN_V1"),

  // Options approval
  APPLICATION_OPTIONS_APPROVED("APPLICATION_OPTIONS_APPROVED_V1"),
  APPLICATION_OPTIONS_APPROVAL_DEADLINE_CHANGE("APPLICATION_OPTIONS_APPROVAL_DEADLINE_CHANGE_V1"),

  // Notify callbacks
  EMAIL_DELIVERY_FAILED("EMAIL_DELIVERY_FAILED_V1"),

  //Public notice
  PUBLIC_NOTICE_APPROVAL_REQUEST("PUBLIC_NOTICE_APPROVAL_REQUEST_V1"),
  PUBLIC_NOTICE_APPROVED("PUBLIC_NOTICE_APPROVED_V1"),
  PUBLIC_NOTICE_REJECTED("PUBLIC_NOTICE_REJECTED_V1"),
  PUBLIC_NOTICE_DOCUMENT_REVIEW_REQUEST("PUBLIC_NOTICE_DOCUMENT_REVIEW_REQUEST_V1"),
  PUBLIC_NOTICE_UPDATE_REQUESTED("PUBLIC_NOTICE_UPDATE_REQUESTED_V1"),
  PUBLIC_NOTICE_WITHDRAWN("PUBLIC_NOTICE_WITHDRAWN_V1"),
  PUBLIC_NOTICE_PUBLICATION("PUBLIC_NOTICE_PUBLICATION_V1"),
  PUBLIC_NOTICE_PUBLICATION_UPDATE("PUBLIC_NOTICE_PUBLICATION_UPDATE_V1");


  private final String templateName;

  NotifyTemplate(String templateName) {
    this.templateName = templateName;
  }

  public String getTemplateName() {
    return this.templateName;
  }
}
