package uk.co.ogauthority.pwa.features.analytics;

public enum AnalyticsEventCategory {

  SAVE_APP_FORM,
  SAVE_APP_FORM_COMPLETE_LATER,

  APPLICATION_SEARCH,
  CONSENT_SEARCH,

  SHOW_DIFFS_APP,
  SHOW_DIFFS_PIPE,
  SHOW_DIFFS_HUOO,

  UPDATE_REQUEST_SENT,

  APPLICATION_SUBMISSION,

  APPLICATION_DELETED,

  PAYMENT_ATTEMPT_STARTED,
  PAYMENT_ATTEMPT_COMPLETED,
  PAYMENT_ATTEMPT_NOT_COMPLETED,

  BACKGROUND_WORKAREA_TAB,

  DOCUMENT_PREVIEW

}