package uk.co.ogauthority.pwa.auth;

public enum PwaUserPrivilege {

  // GENERIC
  PWA_WORKAREA,
  PWA_APPLICATION_SEARCH,
  PWA_ASBUILT_WORKAREA,

  // INDUSTRY + REGULATOR
  PWA_CONSENT_SEARCH,

  // INDUSTRY
  PWA_INDUSTRY,
  PWA_APPLICATION_CREATE,
  PWA_APPLICATION_SUBMIT,

  // REGULATOR
  PWA_REGULATOR,
  PWA_ORG_ADMIN,
  PWA_REGULATOR_ADMIN,
  PWA_REG_ORG_MANAGE,
  PWA_MANAGER,
  PWA_CASE_OFFICER,

  // CONSULTEE
  PWA_CONSULTEE_GROUP_ADMIN,
  PWA_CONSULTEE,

}
