package uk.co.ogauthority.pwa.auth;

import java.util.List;

public enum PwaUserPrivilege {

  // GENERIC
  PWA_ACCESS,
  PWA_WORKAREA,
  PWA_APPLICATION_SEARCH,
  PWA_ASBUILT_WORKAREA,

  // INDUSTRY + REGULATOR
  PWA_CONSENT_SEARCH,

  // INDUSTRY
  PWA_INDUSTRY,
  PWA_APPLICATION_CREATE,
  PWA_APPLICATION_SUBMIT,

  // REGULATOR
  PWA_REGULATOR,
  PWA_ORG_ADMIN,
  PWA_REGULATOR_ADMIN,
  PWA_REG_ORG_MANAGE,
  PWA_MANAGER,
  PWA_CASE_OFFICER,
  PWA_TEMPLATE_CLAUSE_MANAGE,

  // CONSULTEE
  PWA_CONSULTEE_GROUP_ADMIN,
  PWA_CONSULTEE,

  // EXTERNAL ACCESS
  PIPELINE_VIEW;

  public static List<PwaUserPrivilege> asList() {
    return List.of(PwaUserPrivilege.values());
  }


}
