package uk.co.ogauthority.pwa.auth;

public enum PwaUserPrivilege {
  PWA_WORKAREA,
  PWA_ORG_ADMIN,
  PWA_APPLICATION_CREATE,
  PWA_REGULATOR_ADMIN,
  PWA_REG_ORG_MANAGE,
  PWA_MANAGER,
  PWA_CONSULTEE_GROUP_ADMIN,
  PWA_CONSULTEE,
  PWA_INDUSTRY,
  PWA_REGULATOR
}
