package uk.co.ogauthority.pwa.teams;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import uk.co.fivium.energyportal.serviceproviders.epmq.messages.ServiceProviderTeamRolesEpasMessage;
import uk.co.fivium.energyportal.serviceproviders.epmq.messages.ServiceProviderUserTeamRolesDto;
import uk.co.fivium.energyportal.starter.configuration.EnergyPortalAccountsConfigurationProperties;
import uk.co.ogauthority.pwa.auth.AuthenticatedUserAccount;
import uk.co.ogauthority.pwa.integrations.energyportal.people.external.PersonTestUtil;
import uk.co.ogauthority.pwa.integrations.energyportal.webuseraccount.external.UserAccountService;
import uk.co.ogauthority.pwa.integrations.energyportal.webuseraccount.external.WebUserAccountStatus;
import uk.co.ogauthority.pwa.integrations.energyportal.webuseraccount.external.WebUserAccountTestUtil;
import uk.co.ogauthority.pwa.model.auditrevisions.AuditRevisionUtil;
import uk.co.ogauthority.pwa.teams.management.TeamManagementService;

@ExtendWith(MockitoExtension.class)
class TeamRolesUpdateHandlerTest {

  private static final String SERVICE_NAME = "service-name";
  private static final UUID TEAM_ID = UUID.randomUUID();
  private static final Long USER_WUA_ID = 1L;
  private static final Long INVOKING_USER_WUA_ID = 2L;
  private static final ServiceProviderUserTeamRolesDto SERVICE_PROVIDER_USER_TEAM_ROLES_DTO = new ServiceProviderUserTeamRolesDto(
      USER_WUA_ID,
      TEAM_ID.toString(),
      "teamType",
      Set.of(Role.TEAM_ADMINISTRATOR.name())
  );

  @Mock
  private UserAccountService userAccountService;

  @Mock
  private TeamManagementService teamManagementService;

  private final EnergyPortalAccountsConfigurationProperties configurationProperties
      = new EnergyPortalAccountsConfigurationProperties(SERVICE_NAME, "dev1");

  private TeamRolesUpdateHandler teamRolesUpdateHandler;

  private ServiceProviderTeamRolesEpasMessage message;

  @BeforeEach
  void setUp() {
    teamRolesUpdateHandler = new TeamRolesUpdateHandler(
        userAccountService,
        teamManagementService,
        configurationProperties
    );

    message = new ServiceProviderTeamRolesEpasMessage(
        SERVICE_NAME,
        "correlationId",
        Instant.now(),
        SERVICE_PROVIDER_USER_TEAM_ROLES_DTO,
        INVOKING_USER_WUA_ID
    );
  }

  @Test
  void accept_whenMessageNotForService_thenDoNothing() {
    message.setService("different-service");

    teamRolesUpdateHandler.accept(message);

    verify(teamManagementService, never()).setUserTeamRoles(anyLong(), any(), any(), any());
  }

  @Test
  void accept_whenInvalidTeam_thenDoNothing() {
    when(teamManagementService.getTeam(TEAM_ID)).thenReturn(Optional.empty());

    teamRolesUpdateHandler.accept(message);

    verify(teamManagementService, never()).setUserTeamRoles(anyLong(), any(), any(), any());
  }

  @Test
  void accept_whenValidMessage_thenUpdateTeamRoles() {
    var team = TeamTestUtil.newBuilder().build();
    when(teamManagementService.getTeam(TEAM_ID)).thenReturn(Optional.of(team));

    var invokingUserEnergyEnergyPortalUserDto = WebUserAccountTestUtil.createWebUserAccount(
        INVOKING_USER_WUA_ID.intValue(),
        PersonTestUtil.createDefaultPerson(),
        "loginId",
        WebUserAccountStatus.ACTIVE
    );
    when(userAccountService.getWebUserAccount(INVOKING_USER_WUA_ID.intValue()))
        .thenReturn(invokingUserEnergyEnergyPortalUserDto);

    // Verify that the call to teamManagementService are wrapped in withFallbackAuditUser,
    // so that the audit revisions generated by setting the roles have the correct associating wuaIds.
    doAnswer(invocation -> {
      assertThat(AuditRevisionUtil.getFallbackAuditUser())
          .usingRecursiveComparison()
          .isEqualTo(AuthenticatedUserAccount.from(invokingUserEnergyEnergyPortalUserDto));
      return null;
    }).when(teamManagementService).setUserTeamRoles(anyLong(), any(), any(), any());

    teamRolesUpdateHandler.accept(message);

    verify(teamManagementService).setUserTeamRoles(
        USER_WUA_ID,
        team,
        List.of(Role.TEAM_ADMINISTRATOR),
        INVOKING_USER_WUA_ID
    );
  }
}