CREATE TABLE ${datasource.user}.docgen_runs(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY
, di_id INTEGER NOT NULL
, docgen_type VARCHAR2(15) NOT NULL
, status VARCHAR2(500) NOT NULL
, scheduled_by_person_id INTEGER NOT NULL
, scheduled_on TIMESTAMP NOT NULL
, started_on TIMESTAMP
, completed_on TIMESTAMP
, generated_doc BLOB
, CONSTRAINT di_id_fk FOREIGN KEY (di_id) REFERENCES ${datasource.user}.document_instances (id)
);

CREATE INDEX ${datasource.user}.docgen_runs_di_id_idx
ON ${datasource.user}.docgen_runs (di_id);