CREATE TABLE ${datasource.user}.PAD_PROJECT_INFORMATION_LICENCE (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
    , PAD_PROJECT_INFORMATION_ID NUMBER NOT NULL
    , PEARS_LICENSE_NUMBER NUMBER NOT NULL
    , created_timestamp TIMESTAMP NOT NULL
    , CONSTRAINT padpil_padpi_fk FOREIGN KEY (PAD_PROJECT_INFORMATION_ID) REFERENCES ${datasource.user}.PAD_PROJECT_INFORMATION (id)
);
