version: '3.9'

services:

  fox4:
    image: repo1.dev.fivium.local:5000/itportal-fox4-local
    ports:
      - "8080:8080"
    hostname: itportal-fox4-local
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, curl --fail 'http://localhost:8080/engedudev1/fox/nsta/!$$ABOUT' || exit 1]
      interval: 30s
      timeout: 60s
      retries: 3
    environment:
      FOX_CONFIGURE_VIA_ENV: 'true'
      FOX_CONTEXT_PATH: /engedudev1
      FOX_DB_CONNECTION_STRING: (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=db-ogadev1.sb2.dev)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ogadev1)))
      FOX_CONNECTION_KEY: CONN/foxmgr
      FOX_DB_USER: FOXMGR
      FOX_DB_PASSWORD: "dev1"
      FOX_ENGINE_STATUS: DEVELOPMENT
      FOX_SERVICE_LIST: DECC_WEB,DECC_INTRANET,FOI,DECCHR,CWC_INTERNAL,ECASE,ENVIRONMENT_DEV,EDRMS,EIP
      FOX_SUPPORT_PASSWORD: "dev"
      FOX_ADMIN_PASSWORD: "dev"
      FOX_VIRUS_SCANNER_TYPE: IGNORE
      FOX_VIRUS_SCANNER_HOST: "stub"
      FOX_VIRUS_SCANNER_PORT: '3310'
      FOX_VIRUS_SCANNER_TIMEOUT_SECONDS: '60'
      FOX_PUBLIC_ENCRYPTION_KEY: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg+TWjKGalAF1RQpuivcJ92c/YeozR9OIzZ/vPxmjIXYO/GeFvabNc80P7RwWFdHZuMIVsV0EJaA51Z79sM3XBnrhIxt83m/dN8MGXAgV8QNdAsQnhdgdo/ZeP1pyIVAq3fipFFec3EoCdgS8cwtoCGu8UY8IoODv5zphTVOyq4J5hIi5eE4uo5diENC9tSrhj2uCr8lndrzjZnDd9wzuFXQROEAeW0zlZ0KPfcO54/bzRtUdbyZQnIgkcXKhcB9M7zMxVvPVF6+bMFzKGRWsnqcFujg2sjRAG7bx9+txMZAJ/OSY9V2gdmikfSfjJPbFeCPpVwndYrbZi1fzAYCanQIDAQAB'
      FOX_PRIVATE_DECRYPTION_KEY: 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCD5NaMoZqUAXVFCm6K9wn3Zz9h6jNH04jNn+8/GaMhdg78Z4W9ps1zzQ/tHBYV0dm4whWxXQQloDnVnv2wzdcGeuEjG3zeb903wwZcCBXxA10CxCeF2B2j9l4/WnIhUCrd+KkUV5zcSgJ2BLxzC2gIa7xRjwig4O/nOmFNU7KrgnmEiLl4Ti6jl2IQ0L21KuGPa4KvyWd2vONmcN33DO4VdBE4QB5bTOVnQo99w7nj9vNG1R1vJlCciCRxcqFwH0zvMzFW89UXr5swXMoZFayepwW6ODayNEAbtvH363ExkAn85Jj1XaB2aKR9J+Mk9sV4I+lXCd1ittmLV/MBgJqdAgMBAAECggEAG/a9wm1U/8JbYbr3ewErnMfIOXNVUgo4fBhHumIuIx8LyFoOkgo2jzHQCZ6l1BR9C94iiUtGYM/a0z71XLIXv+j3qODgFa00AumXhJW2STZEVxzNoGQUzLmke9wqTIPZwtxAxO5adJ5AbVNNvTqS4Q4ujEA+PRXT53uKO8HeJNyi+PO5sB/sE6y/0BfD0pWb3i4k2XnMDdR892C+4LigGPUIri3VCw9nTDJKQInkNxttUExeQi0dvPkwN+MquSOtq8VcmoayAbn2gZ0A5WgZqJEkczTYuExu2DyF6kEKAMFpbrDsoSTMo0MnBkEOtTqYfqEroD2GWbt0aWjwuLbFQQKBgQDYxDLuN34Y8D7n/5uYUoUV/dIQ1c4JtdM1u/GT0fbAsxOnRXfPcV9etWC4GtG27rBo5c2p7edN+nqickWvQ0RWw3iufh7mNbJIlxtEEGjc3YoTEiblSZUamdQNJVcYX/QjZjBLuWoxSjsrbhyYn0MS1BoGPTqGfk4KHAwWsEgOzQKBgQCbxBljfhkO32s0dvO+JltRRlsic5aiDsyN0EWB8TbPMMulyQZDgulfynxV+vCY8nHiW7EpbkfyjBx7nudUS5Q3pBwTwMPAk2TOLO63muMbBadUVWTol6xouUxxCFKkggdO/rgSm6xuv2glz+dm7ThflOs05TT5INfnWfkwr8gbEQKBgEOYo10/9tWmDafhQM82ZIQgG+LeGZtTlSK7kjELl8wty+Isupj4/MmW/CtNSbqnImIDz6e/JZNemeGQiwSFkIkR+c9ISzB07DzQylLmXx0JBOa/kVuNH68k60iSLV/PhF2Jn2Pt1Ry7zknT050QhSUY+WiarWaFeqaSan6kyEO9AoGAfqJOgbRiatT4Mw8B2fUVCF5KeRe/vsCJTEGmQJ36ETd6WK21ie1EDbxwmPYJ5E42h/BDd4tQsr916IqnRsCrHxEsQmLUwhsSOQwOhvZE7BMMlmNWRkIIyJrcqog5p8SObIpo27fz15WE9jivx93TluFa1wYAqwkofc2H6Sz/YgECgYEAvAEspTpJqsExG+3BT9ekTzgtZ7Axg/anznQpjMrcKbIOs+02yQX5Uk9of3/Ns7veppbfDu+BhhJ2osvT49Ud5cM9aD29QwxaIXyG6QCUoX6uxPRAcZE9+Q+N9lNiOUWczzRiVF+zNzWhedDLhOnVYAVToUn62XA/G/DPpWlMC/U='
      FOX_JQUERY_VERSION: '3.6.0'
      FOX_JQUERY_UI_VERSION: '1.13.2'
      DISABLE_MAC_BASED_CONFIG_ENCRYPTION: 'true'
      JAVA_OPTS: -Xms1024m -Xmx1024m -Duser.country=GB
      LANG: en_GB.UTF-8
      NLS_LANG: ENGLISH_UNITED KINGDOM.AL32UTF8